name: "Tests"

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test-general:
    name: 'Test Package'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
    steps:
      - name: 'Checkout Infrastructure'
        uses: actions/checkout@main
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install QHub
        run: |
          pip install .[dev]
      - name: Black Formatting
        run: |
          black --version
          black qhub --diff
          black --check qhub
      - name: Flake8 Formatting
        run: |
          flake8 --version
          flake8
      - name: Test QHub
        run: |
          pytest --version
          pytest

  test-render-providers:
    name: 'Test QHub Provider'
    runs-on: ubuntu-latest
    needs: test-general
    strategy:
      matrix:
        provider:
          - aws
          - gcp
          - do
    steps:
      - name: 'Checkout Infrastructure'
        uses: actions/checkout@main
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install QHub
        run: |
          pip install .[dev]
      - name: QHub Initialize
        run: |
          qhub init "${{ matrix.provider }}" --project "${{ matrix.provider }}-test" --domain "${{ matrix.provider }}.qhub.dev" --auth-provider github --kubernetes-version "1.18.0" --disable-prompt
      - name: QHub Render
        run: |
          qhub render -c "qhub-config.yaml" -o "qhub-${{ matrix.provider }}-deployment"
      - name: 'Terraform Format'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.13.5
          tf_actions_subcommand: 'fmt'
          tf_actions_working_dir: 'qhub-${{ matrix.provider }}-deployment/terraform-state'
      - name: 'Terraform Format'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.13.5
          tf_actions_subcommand: 'fmt'
          tf_actions_working_dir: 'qhub-${{ matrix.provider }}-deployment/infrastructure'
      - name: QHub Render Artifact
        uses: actions/upload-artifact@master
        with:
          name: "qhub-${{ matrix.provider }}-artifact"
          path: "qhub-${{ matrix.provider }}-deployment"

  test-kubernetes:
    name: "Kubernetes Tests"
    runs-on: ubuntu-latest
    needs: test-render-providers
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@master
      - name: Download and Install Minikube and Kubectl
        run: |
          mkdir -p bin
          pushd bin
          curl -L https://github.com/kubernetes/minikube/releases/download/v1.15.0/minikube-linux-amd64 -o minikube
          chmod +x minikube

          curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.19.0/bin/linux/amd64/kubectl
          chmod +x kubectl

          echo "$PWD" >> $GITHUB_PATH
          popd
      - name: Start Minikube
        run: |
          minikube start --kubernetes-version=1.19.4 --driver=docker --wait=all
      - name: Enable Minikube Ingress
        run: |
          minikube addons enable ingress
      - name: Versions
        run: |
          minikube version
          kubectl version
      - name: Basic Kubectl Checks
        run: |
          kubectl get nodes
          kubectl get namespaces
          kubectl get pods -A
          kubectl get services -A
